/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FirstASN"
 * 	found in "asn/first.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_MyString_H_
#define	_MyString_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MyString */
typedef UTF8String_t	 MyString_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MyString;
asn_struct_free_f MyString_free;
asn_struct_print_f MyString_print;
asn_constr_check_f MyString_constraint;
ber_type_decoder_f MyString_decode_ber;
der_type_encoder_f MyString_encode_der;
xer_type_decoder_f MyString_decode_xer;
xer_type_encoder_f MyString_encode_xer;
per_type_decoder_f MyString_decode_uper;
per_type_encoder_f MyString_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MyString_H_ */
#include <asn_internal.h>
